{{- /*  TODO: - replace with external secret */ -}}
apiVersion: v1
data:
  license: {{ .Values.traffic.ingress.traefikee.license | b64enc | quote }}
kind: Secret
metadata:
  creationTimestamp: null
  name: default-license
