apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: default-license
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: default-license
  data:
  - secretKey: license
    remoteRef:
      key: traefik_ee_license
      property: license
