apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-default-license
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  data:
  - secretKey: license
    remoteRef:
      key: kvv2/traefik_ee_license
      property: license
