# Default values for platform.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
traffic:
  ingress:
    traefikee:
      license: default
observability:
  installController: true
  installResources: false

service:
  port: 8080

database:
  enabled: true

# -- List
databases:
  - name: db-name # instruments local database
    type: rdbms
    environment: local
  - name: prod-db-name # instruments DigitalOcean's managed database service
    type: rdbms
    environment: prod

# Vendor

cert-manager:
  installCRDs: true
