# Default values for platform.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
traffic:
  ingress:
    traefikee:
      license: default
observability:
  installController: true
  installResources: false

# Vendor

cert-manager:
  installCRDs: true
