{{- if .Values.environment.development -}}
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: development-rdbms
  labels:
    crossplane.io/xrd: xpostgresqlinstances.database.example.org
    provider: gcp
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: database.example.org/v1alpha1
    kind: XRDBMS
  resources:
    - name: DevelopmentDB
      base: # Spec Postgresql Pod DB
{{- else -}}
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: production-rdbms
  labels:
    crossplane.io/xrd: xrdbms.database.example.org
    provider: do
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: database.example.org/v1alpha1
    kind: XRDBMS
  resources:
    - name: ProductionDB
      base:
        apiVersion: database.do.crossplane.io/v1alpha1
        kind: DODatabaseCluster
        metadata:
          name: anyvibes
        spec:
          forProvider:
            engine: pg
            version: "13"
            numNodes: 3
            size: db-s-2vcpu-4gb
            region: nyc3
            tags:
              - "from-crossplane"
{{- end -}}
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpostgresqlinstances.database.example.org
spec:
  group: database.example.org
  names:
    kind: XRDBMS
    plural: xrdbmses
  claimNames:
    kind: RDBMS
    plural: RDBMS
---
